### ISSUE TITLE
https://jira.cdisc.org/browse/CORERULES-1766

### ISSUE THREAD

**Issue by FITZPST** [cdisc-org/cdisc-rules-engine#478] opened 2023-07-21 14:13 UTC
**Links to related JIRA Tickets**
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-

**Rule Information**
- **Standard**: ADaMIG 1.3 (all)
- **Rule ID**: ADaM 0169
- **Rule Description**:  CNSR variable should be positive integers , >=0

**Describe the bug**
How to define integer values greater than 0,  want to be able to test only positive whole values are present

**Error returned from Rule Engine**

**Expected behavior**

Solution would be to allow regular expressions (regex) to also work on numeric data

**Screenshots**

**Comment by nhaydel** [comment] 2023-07-21 14:47
Is the greater_than operator not sufficient? Or does this rule also need to ensure that they are not floating point numbers

**Comment by FITZPST** [comment] 2023-07-25 08:38
Hi Nic,

that's the way I interpret it,  if this the requirement, how do we positive numbers containing fractional part.  The machine failure testable criteria is "The value of CNSR is not a positive integer or 0.".  So the greater_than operator will  test for the positive criteria,  how do we distinguish 0 vs 0.1 ,  1 vs 1.01 etc.   Also would 1.0, 2.0,... etc be acceptable values.  Extending regex operator to work on numeric values would provide a solution.  Alternatively could define "numeric types":  integer, float etc

**Comment by gerrycampion** [comment] 2023-11-13 14:23
Duplicate of: https://github.com/cdisc-org/cdisc-rules-engine/issues/164

**Closed** 2023-11-13 14:27 UTC
Labels: bug

**Comment by FITZPST** [comment] 2023-11-14 17:21
Hi Gerry

As this issue is duplicate 164

***@***.***

I’ve updated the Jira workflow as blocked and added comment.  Unsure if this issue fixed cross referencing at Github #164?


***@***.***


BR Steve

**Comment by gerrycampion** [comment] 2023-11-14 22:26
@FITZPST I'm not sure what you are asking. I closed this issue and referenced it in 164. In JIRA, you can reference 164 for this rule.
