### ISSUE TITLE
Version 0.9.6: list of rules (in JSON) contains multiple instances of the same rule(s).

### ISSUE THREAD

**Issue by JozefAerts** [cdisc-org/cdisc-rules-engine#454] opened 2023-07-05 05:27 UTC
With version 0.6.2 (July 1, 2023), using the Windows executable, when running the command "list-rules" and feeding the output into a JSON file, I noticed that in the JSON file produced, each of the rules has multiple instances. For example, for the first rule CORE-000280, rule definition instances start at line 3, 2346, 7188, and 50379. 
Some rules even have more instances. 
Screenshots attached.
We use the JSON output to present the user a list of rules in the GUI of one of our software offerings and allowing them to make selections.
[multiple_rule_instances_json.pdf](https://github.com/cdisc-org/cdisc-rules-engine/files/11954185/multiple_rule_instances_json.pdf)

**Comment by nhaydel** [comment] 2023-07-05 11:46
@JozefAerts this has been addressed before: https://github.com/cdisc-org/cdisc-rules-engine/issues/249 not sure if we want to change our response to it now

**Comment by JozefAerts** [comment] 2023-07-05 11:51
Thanks @nhaydel. Didn't know it was already reported.
No problem - my software checks for the distinct rules when presenting them (for selection) to the user.

**Comment by nhaydel** [comment] 2023-07-05 11:53
Yeah, the "solution" with that rule was just to list rules for a specific standard. The duplicates are caused by one rule having multiple standards. We can address this issue, but the workaround seemed to be sufficient last time it was reported

**Comment by nickdedonder** [comment] 2024-03-12 09:23
Issue has been addressed by #249

**Closed by nickdedonder** 2024-03-12 09:23 UTC
