### ISSUE TITLE
Rule blocked: CORERULES-11 - get key variables

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#344] opened 2023-03-28 20:29 UTC
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-11

**Rule Information**
- **Standard**: SDTM
- **Rule ID**: CG0019
- **Rule Description**: Each record is unique per sponsor defined key variables as documented in the define.xml

**Describe the problem**
This is 1/3 of the solution to writing CG0019.
Get a list of domains and the key variables for the domain from the define.xml. This should handle the cases for
- Split domains
- domains with SUPPs.

In define 2.1,

The (split) dataset name comes from:
`/ODM/Study/MetadataVersion/ItemGroupDef/@name`

The domain/parent domain comes from:
`/ODM/Study/MetadataVersion/ItemGroupDef/@Domain`

The variable keys come from:
`/ODM/Study/MetadataVersion/ItemGroupDef/ItemRef/@KeySequence`
and for SUPP VLM:
`/ODM/Study/MetadataVersion/def:ValueListDef/ItemRef/@KeySequence`

The Variable names come from:
`/ODM/Study/MetadataVersion/ItemDef/@name`
when joining
`/ODM/Study/MetadataVersion/ItemGroupDef/ItemRef/@ItemOID`
with
`/ODM/Study/MetadataVersion/ItemDef/oid`

Additional notes that add to the complexity of this rule:
The KeySequence attribute indicates that the variable referenced by associated ItemRef is part of the dataset key. The value of the attribute identifies the order of the variable within the key. Each variable that is part of the Domain Key must have a KeySequence attribute. If a Supplemental Qualifier variable is part of the Domain key, the KeySequence attribute will be provided in the Value Level Metadata.
The ItemRef@KeySequence attribute applies to:
domain keys for SDTM and SEND
dataset keys for ADaM.

**Describe the solution**
For every domain, a list of Variable names and SUPP QNAMS that are key variables are provided in keysequence order. Split domains and suppquals need to be considered.

**Comment by gerrycampion** [comment] 2023-05-30 15:25
Most of this is straightforward to implement, except the keys from the SUPP VLM.

**Comment by drewcdisc** [comment] 2023-06-05 15:34
@nhaydel , We are assigning this to you in your absence.  We are not certain of your time availability due to Jury Duty and Library Duty.  Let us know what you think.

**Comment by nhaydel** [comment] 2023-06-14 12:51
@RamilCDISC this issue has not resulted in a rule change. Steps to test would include running unit tests, regression tests and whatever else you see fit

**Comment by RamilCDISC** [comment] 2023-06-16 19:35
The changes pushed in this PR are 1/3 part of the functionality that is to implemented for this issue. This ⅓ part changes has been validated using unit tests covering edge cases. These changes are clear from QA.
<img width="1216" alt="344" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/51047038-adaf-4e58-a325-45b555a55ab4">

**Closed** 2023-07-05 15:05 UTC
Labels: enhancement, define cross check
