### ISSUE TITLE
Rule blocked: CORERULES-17

### ISSUE THREAD

**Issue by apalmercdisc** [cdisc-org/cdisc-rules-engine#481] opened 2023-07-25 14:01 UTC
**Links to related JIRA Tickets**
- https://jira.cdisc.org/projects/CORERULES/issues/CORERULES-17

**Rule Information**
- **Standard**: SDTMIG
- **Rule ID**: CG0043
- **Rule Description**:
Variable: AESMIE
Condition: Record present in SUPPAE where SUPPAE.QNAM=AESOSP
Rule: AESMIE = 'Y'

**Describe the bug**
SUPP datasets are not being merged correctly with match datasets

**Error returned from Rule Engine**
Refer to rule CG0043 in the rule editor and the positive test data currently returned 8 negatives when it should be returning none

Note: We think this has to do with the IDVAR IDVARVAL matching or the direction of the parent-child join.
Note: IDVAR and IDVARVAL may not always be populated

**Comment by gerrycampion** [comment] 2023-07-25 15:22
Related to this previous ticket: https://dev.azure.com/cdisc-org/cdisc-core/_workitems/edit/3303

**Comment by ab3263266** [comment] 2024-03-06 19:03
I found 2 issues on bug 
 The first issue is related to the merge, currently in the code there is an option to merge with supp data only when the supp data is on the right side and when you try to merge with supp data when the supp data is on the left it treat it as a normal data and it cause the issues. Should I add the option to merge from SUPP from the left?
Second problem, even when I changed the scoped domain to be AE and did a merge to SUPPAE (so it will be on the right), there was still a problem related to the keys, as it only did the merge on AESEQ and skipped the USUBJID. When I added it, it worked as expected, i.e. for positive data I received 0 errors and for negative data I received the desired number of errors.
I would appreciate help on how to proceed from here.

**Comment by gerrycampion** [comment] 2024-03-06 19:20
@ab3263266 
1. No, we don't need to do this now. We were able to rewrite the rule as AE left join SUPPAE.
2. Yes, if it is not using USUBJID in the join, it should be fixed.

**Comment by RamilCDISC** [comment] 2024-03-27 18:17
The validation for the issue is completed. The bug is successfully solved. Engine properly executes the rule and correctly identify the positive and negative cases. Following tests cases were executed for validation:

- Test with positive data (All rows where QNAM = AESOP corresponding AESMIE=Y)
- Test with negative data (Some rows where QNAM = AESOP corresponding AESMIE != Y)
- Test with example data so that there is no AESMIE= Y (edge case)
- Test with example data so that all values of AESMIE = Y (edge case)
- Test with example data so that AESMIE = Y where QNAM != AESOP (edge case)

The engine gave accurate outputs for all the cases. The code changes are also up to standard and maintain the code quality. 
Following screenshot shows the successful run of the cases.

<img width="1227" alt="481" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/7fac6fb5-0bcb-4693-a3b8-114b746e304a">

**Closed** 2024-04-19 15:20 UTC
Labels: bug, jira reconciled, Rule Blocked
