### ISSUE TITLE
As CORE-ENGINE, There needs to be a way to execute Rule CG0019

### ISSUE THREAD

**Issue by nhaydel** [cdisc-org/cdisc-rules-engine#113] opened 2022-09-12 17:05 UTC
**Links to related JIRA Tickets**
https://jira.cdisc.org/browse/CORERULES-11

**Rule Information**
- **Standard**: SDTM
- **Rule ID**: CG0019
- **Rule Description**: Each record is unique per sponsor defined key variables as documented in the define.xml

This is a define-xml crosscheck. In define 2.1,

The (split) dataset name comes from:
/ODM/Study/MetadataVersion/ItemGroupDef/@Name

The domain/parent domain comes from:
/ODM/Study/MetadataVersion/ItemGroupDef/@Domain

The variable keys come from:
/ODM/Study/MetadataVersion/ItemGroupDef/ItemRef/@KeySequence
and for SUPP VLM:
/ODM/Study/MetadataVersion/def:ValueListDef/ItemRef/@KeySequence

The Variable names come from:
/ODM/Study/MetadataVersion/ItemDef/@Name
when joining
/ODM/Study/MetadataVersion/ItemGroupDef/ItemRef/@ItemOID
with
/ODM/Study/MetadataVersion/ItemDef/@OID

Additional notes that add to the complexity of this rule:
The KeySequence attribute indicates that the variable referenced by associated ItemRef is part of the dataset key. The value of the attribute identifies the order of the variable within the key. Each variable that is part of the Domain Key must have a KeySequence attribute. If a Supplemental Qualifier variable is part of the Domain key, the KeySequence attribute will be provided in the Value Level Metadata.
The ItemRef@KeySequence attribute applies to:
domain keys for SDTM and SEND
dataset keys for ADaM.

**Comment by mhungria** [comment] 2024-03-18 19:29
Added test data to [https://cdisc.sharepoint.com/sites/CORERules/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=5ZwP4m&cid=66d21389%2D65a2%2D4246%2D9328%2Deb1f525607d9&FolderCTID=0x012000DB2B68AD3779324A8BE66373AE3E0E60&id=%2Fsites%2FCORERules%2FShared%20Documents%2FunitTesting%2FSDTMIG%2FCG0019%2FRule%5Fcg0019x%5Ftest&viewid=ecd009a9%2Db73b%2D415b%2D9e41%2Df9d04a69edf4](url)

**Comment by drewcdisc** [comment] 2024-06-17 14:32
This is a duplicate of #345 and is being closed as a dup.

**Closed by drewcdisc** 2024-06-17 14:32 UTC
Labels: define cross check, Rule Blocked
