### ISSUE TITLE
Rule blocked: CORERULES-12 - asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#363] opened 2023-04-04 21:19 UTC
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-12

**Rule Information**
- **Standard**: SDTM
- **Rule ID**: CG0022

**Describe the bug**
When running the attached rule and data, the engine returns an error message
[CG0022.json.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/11153362/CG0022.json.txt)

**Error returned from Rule Engine**
```json
{
  "error": "An unknown exception has occurred",
  "message": "asyncio.run() cannot be called from a running event loop"
}
```

**Expected behavior**
If necessary, the engine should provide a more useful error message.

**Comment by nhaydel** [comment] 2023-04-04 23:13
Does this happen when testing locally or just in the rule editor?

**Comment by nhaydel** [comment] 2023-04-04 23:27
Update I've confirmed it is caused by my update. I have a working fix now, just need to test the standard and ct code with it

**Comment by RamilCDISC** [comment] 2023-04-06 21:46
This issue cannot be confirmed right now if resolved or not. Because the test endpoint is not working properly and giving different errors for different rules and dataset. For example when tested using this rule and dataset [CG0022.json.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/11153362/CG0022.json.txt) the engine returns this error:
	multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\cdisc\cdisc 21-03-2023\cdisc-rules-engine-main\scripts\test_rule.py", line 47, in validate_single_rule
    rule["conditions"]
KeyError: 'conditions'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\cdisc\cdisc 21-03-2023\cdisc-rules-engine-main\core.py", line 452, in <module>
    cli()
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\cdisc\cdisc 21-03-2023\cdisc-rules-engine-main\core.py", line 374, in test
    test_rule(args)
  File "D:\cdisc\cdisc 21-03-2023\cdisc-rules-engine-main\scripts\test_rule.py", line 111, in test
    for rule_result in pool.imap_unordered(
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 870, in next
    raise value
KeyError: 'conditions'

A similar issue is also reported[ here (Issue 320) ](https://github.com/cdisc-org/cdisc-rules-engine/issues/320)and I think we can only confirm iif issue 363 is ready to be closed, after closing of aforementioned issue .

**Comment by nhaydel** [comment] 2023-04-06 23:08
@RamilCDISC This was a change to the test endpoint so a request should be made to the test endpoint in azure not using the test functionality locally

**Comment by RamilCDISC** [comment] 2023-04-13 17:37
The Issue has been successfully tested and resolved. Making POST command using the content of the file in the issue do not give ‘asyncio.run() ‘ error now, Although some other errors are returned which can be seen in the screenshot below, but this issue is related to ‘asyncio.run()’ error which has been resolved,

**Error**:  " "executionStatus": "execution_error" " 

<img width="1512" alt="363" src="https://user-images.githubusercontent.com/113539111/231839415-c4867d14-98be-4ef1-8275-bac719c4113c.png">

**Comment by nhaydel** [comment] 2023-04-13 18:02
The execution errors are an expected part of the engine output @RamilCDISC. They signify a handled exception when running the rule against certain datasets

**Closed** 2023-05-08 15:08 UTC
Labels: bug

**Comment by RamilCDISC** [comment] 2023-07-03 22:01
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Unit Testing:**
Unit Tests were updated based on the changes made. The unit tests covered edge cases and checked all scenarios.

**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**

Regression tests were run to validate that the changes did not affect any functionality of the overall system.


### Test Execution:

> The Tests were run by executing the unit tests using pytest framework. Following command was run for execution of Unit tests:
> python -m pytest tests/unit/test_rule_tester/test_rule_tester.py
> 
> Post request was made using Isomnia, to validate  asyncio.run() error do not occur now
> 
> The regression tests were executed using the following command:
> Python -m pytest test_cli.py
> 

### Results:
After successful running of unit and regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
