### ISSUE TITLE
As a validator I need to have a way to select my custom rules.

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/cdisc-rules-engine#485] opened 2023-07-28 16:30 UTC
- Rule data source should be abstract to allow from different locations
- Rules should be able to be imported from filesystem files in json or yaml format

**Comment by gerrycampion** [comment] 2024-03-25 14:10
Duplicate of [#83](https://github.com/cdisc-org/ddf-core-poc/issues/83)

**Closed by gerrycampion** 2024-03-25 14:10 UTC
