### ISSUE TITLE
AS CORE-ENGINE, is_unique_set and is_not_unique_set should ignore missing variables in the value list

### ISSUE THREAD

**Issue by nhaydel** [cdisc-org/cdisc-rules-engine#119] opened 2022-09-12 17:11 UTC
Rule: CG0562
Refer to JIRA ticket: https://jira.cdisc.org/browse/CORERULES-249

is_unique_set and is_not_unique_set use a "value" list to indicate which variables should be included in the uniqueness check. Some datasets may not have all of the variables listed. Currently, the engine will output the following message:
"error":"Column not found in data"
Instead, the engine should ignore the missing columns and perform the operation on the intersection of:
the columns provided in the "value" list
the columns that exist in the dataset.

**Comment by alexfurmenkov** [comment] 2022-09-22 13:24
The issue is addressed by the following PR: https://github.com/cdisc-org/business-rules/pull/55

**Comment by RamilCDISC** [comment] 2023-04-04 21:17
Upon reviewing the changes in the code of is_unique_set function [here](https://github.com/cdisc-org/business-rules/blob/3b8036995fb7f2bf75c1696dbe464f58259dbaf2/business_rules/operators.py), It is observed that code will not output message "error":"Column not found in data" when some dataset may not have all of the variables listed. The code still checks the presence of column in the dataset, but if a column is missing it just ignores it and moves to the next one. The following code part implements this 
 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/113539111/229924293-1e96041a-c97e-4a2c-a94b-ffb8ff6bc5e5.png">

The if condition checks the presence of column in the dataset and if it is missing, the if condition fails and loop continues. 
The code also fulfils the requirement of performing operation on the intersection of the columns provided in the "value" list and the columns that exist in the dataset.
The following code part implements it.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/113539111/229924426-d86ecea0-09cb-4201-8a1d-cebf5a602b24.png">
 
**Conclusion:** Hence the acceptance criteria for the issue 119 is fulfilled and can be closed successfully.

**Closed** 2023-05-08 15:08 UTC
Labels: bug

**Comment by RamilCDISC** [comment] 2023-07-01 22:09
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Unit Testing:**
Unit Tests were updated based on the changes made to the operators in operators.py file in the Business rules repository. The unit tests covered edge cases and checked all scenarios.such as the case when the value list contains all variables, and when it does not contain all variables. These tests help in ensuring that the function is properly implemented and bug free. 
**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.


### Test Cases:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-cae380ae-7fff-c60b-9d4b-62dfd893e423"><div dir="ltr" style="margin-left:0.75pt;" align="left">

Test Case Description | Function Name | Expected Result | Result
-- | -- | -- | --
Test if is_unique_set correctly identifies unique sets based on the "ARM" column and the "LAE" column as the comparator. | test_is_unique_set | Expected result: A pandas Series with [True, True, True, True] | Passed
Test if is_unique_set correctly identifies unique sets based on the "ARM" column and a single element list ["LAE"] as the comparator. | test_is_unique_set | Expected result: A pandas Series with [True, True, True, True] | Passed
Test if is_unique_set correctly identifies unique sets based on the "ARM" column and a single element list ["TAE"] as the comparator. | test_is_unique_set | Expected result: A pandas Series with [False, False, True, True] | Passed
Test if is_unique_set correctly identifies unique sets based on the "ARM" column and a two-element list ["TAE", "NOT_IN_DS"] as the comparator. | test_is_unique_set | Expected result: A pandas Series with [False, False, True, True] | Passed
Test if is_unique_set correctly identifies unique sets based on the "ARM" column and the "TAE" column as the comparator. | test_is_unique_set | Expected result: A pandas Series with [False, False, True, True] | Passed
PassedTest if is_unique_set correctly identifies unique sets when column prefixes are specified in the DataframeType object. | test_is_unique_set | Expected result: A pandas Series with [True, True, True, True] | Passed
Test if is_unique_set correctly identifies unique sets when column prefixes are specified and a single element list ["--F"] is used as the comparator. | test_is_unique_set | Expected result: A pandas Series with [True, True, True, True] | Passed
Test if is_not_unique_set correctly identifies non-unique sets based on the "ARM" column and the "LAE" column as the comparator. | test_is_not_unique_set | Expected result: A pandas Series with [False, False, False, False] | Passed
Test if is_not_unique_set correctly identifies non-unique sets based on the "ARM" column and a single element list ["LAE"] as the comparator. | test_is_not_unique_set | Expected result: A pandas Series with [False, False, False, False] | Passed
Test if is_not_unique_set correctly identifies non-unique sets based on the "ARM" column and a single element list ["TAE"] as the comparator. | test_is_not_unique_set | Expected result: A pandas Series with [True, True, False, False] | Passed
Test if is_not_unique_set correctly identifies non-unique sets based on the "ARM" column and a two-element list ["TAE", "NOT_IN_DS"] as the comparator. | test_is_not_unique_set | Expected result: A pandas Series with [True, True, False, False] | Passed
Test if is_not_unique_set correctly identifies non-unique sets based on the "ARM" column and the "TAE" column as the comparator. | test_is_not_unique_set | Expected result: A pandas Series with [True, | Passed
Test if is_not_unique_set correctly identifies non-unique sets based on the "ARM" column and the "TAE" column as the comparator. | test_is_not_unique_set | Expected result: A pandas Series with [True, True, False, False] | Passed
Test if is_not_unique_set correctly identifies non-unique sets when column prefixes are specified in the DataframeType object. | test_is_not_unique_set | Expected result: A pandas Series with [False, False, False, False] |  
Test if is_not_unique_set correctly identifies non-unique sets when column prefixes are specified and a single element list ["--F"] is used as the comparator. | test_is_not_unique_set | Expected result: A pandas Series with [False, False, False, False] |  

</div></b>

### Test Execution:

> The Tests were run by executing the unit tests using pytest framework. Following command was run for execution of Unit tests:
> python -m pytest tests/test_operators.py
> 
> The regression tests were executed using the following command:
> Python -m pytest test_cli.py
> 

### Results:
After successful running of unit and regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
